---

  - name: Check to see if pip is already installed.
    command: "pip --version"
    ignore_errors: false
    changed_when: false # read-only task
    check_mode: no
    register: pip_is_installed
 
  - name: Ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - gcc 
      - gcc-c++ 
      - python-devel 
      - cairo-devel 
      - gobject-introspection-devel 
      - cairo-gobject-devel 
      - ansible
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


  - name: Installing all the required library
    pip:
      name: 
        - ansible>=2.7
        - pexpect
        - asn1crypto>=0.24.0
        - cryptography>=2.1.4
        - enum34>=1.1.6
        - httplib2>=0.9.2
        - idna>=2.6
        - ipaddress>=1.0.17
        - Jinja2>=2.10
        - keyring>=10.6.0
        - keyrings.alt>=3.0
        - MarkupSafe>=1.0
        - paramiko>=2.0.0
        - pyasn1>=0.4.2
        - pycrypto>=2.6.1
        - pygobject>=3.26.1
        - pyxdg>=0.25
        - PyYAML>=3.12
        - SecretStorage>=2.3.1
        - six>=1.11.0
        - softlayer
      state: forcereinstall

  - name: Check to see if slcli is already installed.
    command: " slcli --version"
    ignore_errors: false
    changed_when: false # read-only task
    check_mode: no
    register: slcli_is_installed



  - name: Creating Openssh_keypair
    openssh_keypair:
      path: "{{role_path}}/files/sl_ssh_rsa"
      size: 2048
      force: True

  - name: adding ssh key to localhost
    shell: |
      exec ssh-agent bash 
      ssh-add {{role_path}}/files/sl_ssh_rsa
    ignore_errors: false  
  
  - name: Write out Softlayer config file  
    template:
      src: "{{ role_path }}/templates/.softlayer.j2"
      dest: "{{ role_path }}/files/.softlayer"

  
  - name: Set Facts for softlayer configuration path
    set_fact: softlayer_conf="{{ role_path }}/files/.softlayer"

  - name: If follow=yes, create a link to softlayer config file
    copy:
      src: "{{ softlayer_conf }}"
      remote_src: yes
      dest: ~/  # link to /path/to/file
      follow: yes

  - name: Copy RSA file to artifacts to SoftLayer config file
    copy:
      src: "{{role_path}}/files/sl_ssh_rsa"
      remote_src: yes
      dest: "{{role_path}}/../../artifacts/sl_ssh_rsa" # link to /path/to/file
     
  
  - name: Copy RSA file to artifacts to Softlayer config file
    copy:
      src: "{{role_path}}/files/sl_ssh_rsa.pub"
      remote_src: yes
      dest: "{{role_path}}/../../artifacts/sl_ssh_rsa.pub" # link to /path/to/file



  - name: Get the ssh key-id by name ocp-key
    register: contentof_all_sl_sshkeys
    shell: "slcli  sshkey list | grep ocp-key"
    ignore_errors: true
  
  #- debug: var=contentof_all_sl_sshkeys.stdout_lines
 
  - set_fact:
      all_sl_ocp_key: "{{ contentof_all_sl_sshkeys.stdout_lines }}"
  
  - name: Please go through all the previous OCP-key and delete it before adding it
    shell: slcli  -y sshkey remove {{item.split(" ")[0]}}
    with_items: "{{ all_sl_ocp_key }}"
   
  - name: Adding sshkey to the softlayer
    command: "slcli sshkey add -f {{role_path}}/files/sl_ssh_rsa.pub ocp-key"
  
  
  - name: Get the ssh key-id
    register: contentof_sl_sshkeys
    shell: "slcli  sshkey list"
   
  
  # - debug:
  #     msg: "{{ contentof_sl_sshkeys.stdout_lines | list }}"

  - name: Get the VLAN id using VLAN number
    register: contentof_sl_vlan_id
    shell: "slcli vlan list | grep {{ sl_datacenter }} | grep {{ sl_private_vlan }} | awk '{print $1}'"
  
  - name: Set fact variable for VLAN id 
    set_fact:
      sl_vlan_id: "{{ contentof_sl_vlan_id.stdout }}"
  
  - debug:
      msg: "{{ contentof_sl_vlan_id }}"


  
  