#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.





menuentry 'coreos 4.X' {
     linux16 (hd0,msdos2)/tmp/coreos.hsk

}

